### ISSUE TITLE
Agree on a branching model

### ISSUE THREAD

**Issue by rollcat** [unit9/gae-secure-scaffold-python#3]
Currently the model seems to be:
- Work happens on a `feature/*` branch
- PR to merge to `develop`
- ... merge to `master` - when?

I would argue that this model is broken:
- There's no clear indicator of when changes on develop should propagate to master
- There's no CI or CD system in place, and we're not tying the branching model with GAE deployments, (there are no deployments at all actually), so the condition of "merging to master = deploy live" does not apply
- It creates confusion because Github allows only one "default" branch - if it's "master", then all PRs land on master by default. If it's develop, all we've achieved is we've renamed "master" to "develop" and master will end up being 7441 commits behind 90% of the time.

I would suggest we adopt a simple model where each feature branch is merged directly to master after a review. It works extremely well on the [Cookbook](https://bitbucket.org/u9/cookbook/pull-requests/?displaystatus=merged).

@maciejzasada @krzysztofnowak discuss.

**Comment by krzysztofnowak** [comment]
If there is no option to properly use develop and master then ok to use master as default branch

**Comment by maciejzasada** [comment]
I've never been in favour of that but we can try...
IMHO the merge from develop to master should happen when someone pulls latest develop, tests it out and verifies it's working. Otherwise you can test the feature branch but it's out of context.
So it would be a "no" for me but I'll be happy to forfeit if everyone else votes for that idea ;)

**Comment by maciejzasada** [comment]
Also to rephrase - as we all agree we have no CI / CD, the only place for an "integration test" to happen is the develop branch. Even if two feature branches don't conflict and each of them works perfectly fine, after both are merged to master, master can break. If we do it on develop, we ensure master remains stable all the time and we use develop as an integration test environment.
Again, I'm voting to keep the current branching model.

**Comment by rollcat** [comment]
> IMHO the merge from develop to master should happen when **someone** pulls latest develop, tests it out and verifies it's working.

Emphasis mine. Who? When?

> Otherwise you can test the feature branch but it's out of context.

This is your duty as a reviewer. If you can't test the feature branch, you shouldn't approve a PR.

> as we all agree we have no CI / CD, the only place for an "integration test" to happen is the develop branch

https://github.com/unit9/gae-secure-scaffold-python/issues/6

> Even if two feature branches don't conflict and each of them works perfectly fine, after both are merged to master, master can break.

Valid point, and this is when you create a hotfix branch.

**Comment by rollcat** [comment]
@maciejzasada also see https://github.com/unit9/gae-secure-scaffold-python/pull/7 and https://app.shippable.com/runs/570d151d5f74910c00e99ef3 - Shippable & Github will inform you if merging a pull request to master would break the build.

**Comment by rollcat** [comment]
Master it is.
